### ISSUE TITLE
Reported Term

### ISSUE THREAD

**Issue by abhinav-kashyap-asus** [Bayer-Group/xtars-naacl2022#1]
Hi, all the other papers that perform medical coding use the MIMIC datasets.  The context for the model is the discharge summary which is a long document. I find that in your paper it is the "Reported Term". What is the average length of the reported term and how did you obtain this "Reported term"?

**Comment by angeloziletti** [comment]
Thanks for your question, and apologies for the late reply. 

In our dataset, the "Reported Term" is already given (it comes from the clinical trial data collection process). The "Reported Term" is quite short, usually a few words long.

To apply the xTARS methodology to MIMIC, you could make a two-step approach:
1. apply a NER model to extract the entities from the long text
2. use xTARS to associate the correct code to the extracted entities (i.e., named entity normalization)

I have done it myself for a project (on another dataset) using for example Stanza for NER (step 1), and then applying xTARS on the detected entities.

I hope this helps!

**Comment by abhinav-kashyap-asus** [comment]
Thanks for the reply :) I will give this a try
